### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by tomohideshibata** [yuukimiyo/wikiextractor2sqlite#1]
Thank you for releasing the useful codes!
I have found a small typo.
In the last line in "Example Usage", `pages` should be ` extracted_page`.

```
sqlite3 wikipedia.db "select count(*) from pages;"
```

Thanks.

**Comment by yuukimiyo** [comment]
Thank you [tomohideshibata](https://github.com/tomohideshibata)! I had fixed the problem you pointed out.
